### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dhaavi** [aead/ecdh#3]
Please tag a new release to make recent changes available to go dependency mgmt systems (go mod and dep).

Reminder from https://github.com/golang/go/wiki/Modules#publishing-a-release:

> A new module version may be published by pushing a tag to the repository that contains the module source code. The tag is formed by concatenating two strings: a prefix and a version.

Next tag could be `v0.1.1` or `v0.2.0`.

**Comment by aead** [comment]
@dhaavi In general you can require that `go` uses a specific commit as a module dependency. However, tagged latest commit as `v0.2.0`.
